"""add usage_count to ai_learning_templates

Revision ID: 16e96fcde85d
Revises: 406d60af15f9
Create Date: 2026-05-29 08:22:45.577808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e96fcde85d'
down_revision: Union[str, None] = '406d60af15f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_learning_templates', sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_learning_templates', 'usage_count')
    # ### end Alembic commands ###
