"""Add AIParsingLog

Revision ID: 18cab491aa8d
Revises: 16e96fcde85d
Create Date: 2026-05-30 01:53:42.819584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18cab491aa8d'
down_revision: Union[str, None] = '16e96fcde85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_parsing_logs_tenant_id'), table_name='ai_parsing_logs')
    op.drop_index(op.f('ix_ai_parsing_logs_id'), table_name='ai_parsing_logs')
    op.drop_table('ai_parsing_logs')
    # ### end Alembic commands ###
