"""redesign_master_data_global_and_tenant

Revision ID: 3028a945ea11
Revises: 4c1c30d2dd85
Create Date: 2026-06-06 14:46:50.985639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3028a945ea11'
down_revision: Union[str, None] = '4c1c30d2dd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 0. Drop HNSW indexes FIRST because they depend on halfvec and cannot automatically handle type change to vector
    op.execute("DROP INDEX IF EXISTS ix_ai_templates_embedding_hnsw;")
    op.execute("DROP INDEX IF EXISTS ix_products_embedding_hnsw;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    
    op.create_table('product_unit_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=20), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_unit_conversions_id'), 'product_unit_conversions', ['id'], unique=False)
    
    op.create_table('tenant_inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('last_purchase_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('moving_average_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('static_stock', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'product_id', name='uq_tenant_inventory_product')
    )
    op.create_index(op.f('ix_tenant_inventories_id'), 'tenant_inventories', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_inventories_product_id'), 'tenant_inventories', ['product_id'], unique=False)
    op.create_index(op.f('ix_tenant_inventories_tenant_id'), 'tenant_inventories', ['tenant_id'], unique=False)
    
    op.create_table('tenant_pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rule_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_pricing_rules_id'), 'tenant_pricing_rules', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_pricing_rules_product_id'), 'tenant_pricing_rules', ['product_id'], unique=False)
    op.create_index(op.f('ix_tenant_pricing_rules_tenant_id'), 'tenant_pricing_rules', ['tenant_id'], unique=False)
    
    op.create_table('tenant_product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pricing_method', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'product_id', name='uq_tenant_price_product')
    )
    op.create_index(op.f('ix_tenant_product_prices_id'), 'tenant_product_prices', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_product_prices_product_id'), 'tenant_product_prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_tenant_product_prices_tenant_id'), 'tenant_product_prices', ['tenant_id'], unique=False)
    
    op.alter_column('ai_learning_templates', 'embedding',
               existing_type=pgvector.sqlalchemy.halfvec.HALFVEC(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('base_unit', sa.String(length=20), nullable=False, server_default='pcs'))
    op.alter_column('products', 'embedding',
               existing_type=pgvector.sqlalchemy.halfvec.HALFVEC(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_constraint('uq_product_tenant_sku', 'products', type_='unique')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_constraint('products_tenant_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'product_categories', ['category_id'], ['id'])
    op.drop_column('products', 'unit')
    op.drop_column('products', 'min_stock_level')
    op.drop_column('products', 'current_stock')
    op.drop_column('products', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('current_stock', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, server_default='0'))
    op.add_column('products', sa.Column('min_stock_level', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, server_default='0'))
    op.add_column('products', sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False, server_default='pcs'))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_tenant_id_fkey', 'products', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_unique_constraint('uq_product_tenant_sku', 'products', ['tenant_id', 'sku'])
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    
    op.alter_column('products', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.halfvec.HALFVEC(dim=3072),
               existing_nullable=True)
    op.drop_column('products', 'base_unit')
    op.drop_column('products', 'category_id')
    
    op.alter_column('ai_learning_templates', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.halfvec.HALFVEC(dim=3072),
               existing_nullable=True)
               
    # Re-create HNSW indexes
    op.execute("CREATE INDEX IF NOT EXISTS ix_products_embedding_hnsw ON products USING hnsw (embedding halfvec_cosine_ops) WITH (m = 16, ef_construction = 64);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_ai_templates_embedding_hnsw ON ai_learning_templates USING hnsw (embedding halfvec_cosine_ops) WITH (m = 16, ef_construction = 64);")

    op.drop_index(op.f('ix_tenant_product_prices_tenant_id'), table_name='tenant_product_prices')
    op.drop_index(op.f('ix_tenant_product_prices_product_id'), table_name='tenant_product_prices')
    op.drop_index(op.f('ix_tenant_product_prices_id'), table_name='tenant_product_prices')
    op.drop_table('tenant_product_prices')
    op.drop_index(op.f('ix_tenant_pricing_rules_tenant_id'), table_name='tenant_pricing_rules')
    op.drop_index(op.f('ix_tenant_pricing_rules_product_id'), table_name='tenant_pricing_rules')
    op.drop_index(op.f('ix_tenant_pricing_rules_id'), table_name='tenant_pricing_rules')
    op.drop_table('tenant_pricing_rules')
    op.drop_index(op.f('ix_tenant_inventories_tenant_id'), table_name='tenant_inventories')
    op.drop_index(op.f('ix_tenant_inventories_product_id'), table_name='tenant_inventories')
    op.drop_index(op.f('ix_tenant_inventories_id'), table_name='tenant_inventories')
    op.drop_table('tenant_inventories')
    op.drop_index(op.f('ix_product_unit_conversions_id'), table_name='product_unit_conversions')
    op.drop_table('product_unit_conversions')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
