"""add journal mapping and vector rag columns

Revision ID: 3b21bd4bb078
Revises: cee1be0cd891
Create Date: 2026-05-31 15:05:26.099720

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3b21bd4bb078'
down_revision: Union[str, None] = 'cee1be0cd891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', postgresql.ENUM(name='transactiontype', create_type=False), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'transaction_type', name='uq_mapping_tenant_type')
    )
    op.create_index(op.f('ix_journal_mappings_id'), 'journal_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_journal_mappings_tenant_id'), 'journal_mappings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_journal_mappings_transaction_type'), 'journal_mappings', ['transaction_type'], unique=False)
    op.create_table('journal_mapping_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], ['journal_mappings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_mapping_lines_id'), 'journal_mapping_lines', ['id'], unique=False)
    op.create_index(op.f('ix_journal_mapping_lines_mapping_id'), 'journal_mapping_lines', ['mapping_id'], unique=False)
    op.add_column('ai_learning_templates', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_learning_templates', 'embedding')
    op.drop_index(op.f('ix_journal_mapping_lines_mapping_id'), table_name='journal_mapping_lines')
    op.drop_index(op.f('ix_journal_mapping_lines_id'), table_name='journal_mapping_lines')
    op.drop_table('journal_mapping_lines')
    op.drop_index(op.f('ix_journal_mappings_transaction_type'), table_name='journal_mappings')
    op.drop_index(op.f('ix_journal_mappings_tenant_id'), table_name='journal_mappings')
    op.drop_index(op.f('ix_journal_mappings_id'), table_name='journal_mappings')
    op.drop_table('journal_mappings')
    # ### end Alembic commands ###
