"""Add AIModelQuota

Revision ID: 3bc5d2df4b67
Revises: 18cab491aa8d
Create Date: 2026-05-30 06:47:31.352571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bc5d2df4b67'
down_revision: Union[str, None] = '18cab491aa8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('usage_date', sa.DateTime(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'usage_date', name='uq_model_quota_date')
    )
    op.create_index(op.f('ix_ai_model_quotas_id'), 'ai_model_quotas', ['id'], unique=False)
    op.alter_column('ai_parsing_logs', 'processor',
               existing_type=postgresql.ENUM('LOCAL', 'OLLAMA', 'GEMINI', name='parsertype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_parsing_logs', 'processor',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('LOCAL', 'OLLAMA', 'GEMINI', name='parsertype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_model_quotas_id'), table_name='ai_model_quotas')
    op.drop_table('ai_model_quotas')
    # ### end Alembic commands ###
