"""add ai learning templates

Revision ID: 406d60af15f9
Revises: 8e7f7373e369
Create Date: 2026-05-28 11:31:55.215852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406d60af15f9'
down_revision: Union[str, None] = '8e7f7373e369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_learning_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_learning_templates_id'), 'ai_learning_templates', ['id'], unique=False)
    op.create_index(op.f('ix_ai_learning_templates_tenant_id'), 'ai_learning_templates', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_learning_templates_tenant_id'), table_name='ai_learning_templates')
    op.drop_index(op.f('ix_ai_learning_templates_id'), table_name='ai_learning_templates')
    op.drop_table('ai_learning_templates')
    # ### end Alembic commands ###
