"""Add contact_id to InventoryLog

Revision ID: 5113e41f145a
Revises: 6e8a75fca3b1
Create Date: 2026-05-25 11:54:52.573353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5113e41f145a'
down_revision: Union[str, None] = '6e8a75fca3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
