"""Add contact_id to InventoryLog

Revision ID: 6e8a75fca3b1
Revises: c86de36ce2b8
Create Date: 2026-05-25 11:53:49.608018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8a75fca3b1'
down_revision: Union[str, None] = 'c86de36ce2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_logs', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventory_logs_contact_id'), 'inventory_logs', ['contact_id'], unique=False)
    op.create_foreign_key(None, 'inventory_logs', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_logs', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_logs_contact_id'), table_name='inventory_logs')
    op.drop_column('inventory_logs', 'contact_id')
    # ### end Alembic commands ###
