"""add status to transaction and contact relationship

Revision ID: 8636e58d79e7
Revises: 16c4b1b11f18
Create Date: 2026-05-25 17:01:55.711390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8636e58d79e7'
down_revision: Union[str, None] = '16c4b1b11f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type explicitly for Postgres if it doesn't exist
    op.execute("DO $$ BEGIN CREATE TYPE transactionstatus AS ENUM('DRAFT', 'POSTED'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    # 1. Add as nullable
    op.add_column('transactions', sa.Column('status', sa.Enum('DRAFT', 'POSTED', name='transactionstatus'), nullable=True))
    
    # 2. Fill existing data
    op.execute("UPDATE transactions SET status = 'POSTED' WHERE status IS NULL")
    
    # 3. Set to NOT NULL
    op.alter_column('transactions', 'status', nullable=False)
    
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_column('transactions', 'status')
    
    # Drop ENUM type explicitly
    op.execute("DROP TYPE transactionstatus")
    # ### end Alembic commands ###
