"""add raw_ocr_text to ocrtask

Revision ID: 8e7f7373e369
Revises: d90631c263ad
Create Date: 2026-05-28 09:39:59.809521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7f7373e369'
down_revision: Union[str, None] = 'd90631c263ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_tasks', sa.Column('raw_ocr_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocr_tasks', 'raw_ocr_text')
    # ### end Alembic commands ###
