"""Add MultiTenant to Accounts Transactions Products Contacts

Revision ID: c86de36ce2b8
Revises: d5b573c51a65
Create Date: 2026-05-21 16:28:40.748714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86de36ce2b8'
down_revision: Union[str, None] = 'd5b573c51a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_account_tenant_code', 'accounts', ['tenant_id', 'code'])
    op.create_foreign_key(None, 'accounts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('contacts', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_contact_tenant_name_type', 'contacts', ['tenant_id', 'name', 'contact_type'])
    op.create_foreign_key(None, 'contacts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_product_tenant_sku', 'products', ['tenant_id', 'sku'])
    op.create_foreign_key(None, 'products', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('transactions', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_transactions_reference_no'), table_name='transactions')
    op.create_index(op.f('ix_transactions_reference_no'), 'transactions', ['reference_no'], unique=False)
    op.create_index(op.f('ix_transactions_tenant_id'), 'transactions', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_transaction_tenant_ref', 'transactions', ['tenant_id', 'reference_no'])
    op.create_foreign_key(None, 'transactions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint('uq_transaction_tenant_ref', 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_tenant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_no'), table_name='transactions')
    op.create_index(op.f('ix_transactions_reference_no'), 'transactions', ['reference_no'], unique=True)
    op.drop_column('transactions', 'tenant_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint('uq_product_tenant_sku', 'products', type_='unique')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_column('products', 'tenant_id')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint('uq_contact_tenant_name_type', 'contacts', type_='unique')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_column('contacts', 'tenant_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint('uq_account_tenant_code', 'accounts', type_='unique')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=True)
    op.drop_column('accounts', 'tenant_id')
    # ### end Alembic commands ###
