"""Add tenant_id to OCRTask

Revision ID: cee1be0cd891
Revises: 3bc5d2df4b67
Create Date: 2026-05-30 07:41:42.413777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee1be0cd891'
down_revision: Union[str, None] = '3bc5d2df4b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_tasks', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ocr_tasks_tenant_id'), 'ocr_tasks', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'ocr_tasks', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ocr_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_ocr_tasks_tenant_id'), table_name='ocr_tasks')
    op.drop_column('ocr_tasks', 'tenant_id')
    # ### end Alembic commands ###
